name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven
        run: mvn --batch-mode -Pci clean package
      - name: CodeCov
        uses: codecov/codecov-action@v1
  IT-sandbox-agora-realm:
    needs: build
    runs-on: ubuntu-latest
    env:
      IM_BASE_URI: http://a1-hsb.easemob.com
      IM_REALM: AGORA_REALM
      IM_APPKEY: ${{ secrets.IM_APPKEY_SANDBOX }}
      IM_APP_ID: ${{ secrets.IM_APP_ID_SANDBOX }}
      IM_APP_CERT: ${{ secrets.IM_APP_CERT_SANDBOX }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven
        run: mvn -pl im-sdk-core --batch-mode -Pci clean test -D test="AgoraTokenIT" -D failIfNoTests=false

