name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven
        run: mvn --batch-mode -Pci clean package
      - name: CodeCov
        uses: codecov/codecov-action@v1
  IT-ebs:
    needs: build
    runs-on: ubuntu-latest
    env:
      IM_APPKEY: ${{ secrets.IM_APPKEY_EBS }}
      IM_CLIENT_ID: ${{ secrets.IM_CLIENT_ID_EBS }}
      IM_CLIENT_SECRET: ${{ secrets.IM_CLIENT_SECRET_EBS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven
        run: mvn --batch-mode -Pci clean test -D test="*IT" -D failIfNoTests=false

