name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  IT-ebs-metadata:
    runs-on: ubuntu-latest
    env:
      IM_APPKEY: ${{ secrets.IM_APPKEY_EBS }}
      IM_CLIENT_ID: ${{ secrets.IM_CLIENT_ID_EBS }}
      IM_CLIENT_SECRET: ${{ secrets.IM_CLIENT_SECRET_EBS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven
        run: mvn -pl im-sdk-core --batch-mode -Pci clean test -D test="MetadataIT" -D failIfNoTests=false
